// <auto-generated />
namespace IdeaCreationManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Grades_AverageGrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Grades_AverageGrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201706031007337_Grades_AverageGrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
